"""Regression diagnosis: bisect, replay, shrink, and trace."""

from .bisect import (
    BisectCache,
    BisectReport,
    BisectResult,
    RegressionDecision,
    RegressionStatus,
    RunOutcome,
    StochasticBisector,
    SubprocessGit,
    bisect,
    bisect_commits,
    decide_regression,
    git_bisect,
)
from .replay import (
    Incident,
    ReplayEngine,
    ReplayIncident,
    ReplayResult,
    TorchStateAdapter,
    replay,
    replay_incident,
    restore_rng_state,
    snapshot_state,
)
from .report import DiagnosisReport, Report, as_dict, to_json
from .runner import ExperimentRunner, RunResult, SeedRun, evaluate_runner, run_many
from .shrink import (
    ShrinkReport,
    ShrinkResult,
    capsule_replay_input,
    ddmin,
    persist_shrink_capsule,
    shrink,
    shrink_capsule,
    shrink_columns,
    shrink_rows,
    shrink_tensor,
    shrink_tokens,
)
from .trace import (
    RingBufferTrace,
    TensorTracer,
    TraceBuffer,
    TraceEvent,
    attach_torch_hooks,
    detect_non_finite,
    tensor_event,
    trace_incident,
)

__all__ = [
    "BisectResult",
    "BisectCache",
    "BisectReport",
    "DiagnosisReport",
    "ExperimentRunner",
    "ReplayEngine",
    "ReplayResult",
    "ReplayIncident",
    "Incident",
    "RegressionDecision",
    "RegressionStatus",
    "Report",
    "RunResult",
    "RunOutcome",
    "ShrinkResult",
    "ShrinkReport",
    "StochasticBisector",
    "SubprocessGit",
    "SeedRun",
    "TensorTracer",
    "RingBufferTrace",
    "TraceEvent",
    "TorchStateAdapter",
    "TraceBuffer",
    "attach_torch_hooks",
    "as_dict",
    "bisect",
    "bisect_commits",
    "decide_regression",
    "ddmin",
    "git_bisect",
    "replay",
    "replay_incident",
    "restore_rng_state",
    "snapshot_state",
    "shrink",
    "shrink_capsule",
    "capsule_replay_input",
    "persist_shrink_capsule",
    "shrink_columns",
    "shrink_rows",
    "shrink_tensor",
    "shrink_tokens",
    "tensor_event",
    "trace_incident",
    "detect_non_finite",
    "evaluate_runner",
    "run_many",
    "to_json",
]
