"""Backend parity utilities for callable and optional framework models."""

from .adapters import CallableAdapter, ONNXRuntimeAdapter, PyTorchAdapter, as_adapter
from .backends import (
    BackendAdapter,
    BackendError,
    BackendSpec,
    CallableBackendAdapter,
    FunctionBackendAdapter,
    GenericBackendAdapter,
    ONNXAdapter,
    ONNXRuntimeBackendAdapter,
    OnnxRuntimeBackendAdapter,
    OptionalDependencyError,
    PyTorchBackendAdapter,
    TorchAdapter,
    TorchBackendAdapter,
    as_backend,
    load_backend,
    parse_backend_spec,
    predict_batch,
)
from .compare import (
    ComparisonResult,
    OutputComparison,
    ParityCaseResult,
    ParityChecker,
    ParityComparator,
    ParityDivergence,
    ParityReport,
    ParityResult,
    Tolerance,
    TolerancePolicy,
    Tolerances,
    compare_batch,
    compare_models,
    compare_outputs,
    parity,
)
from .generators import RepresentativeInputGenerator
from .inputs import (
    InputCase,
    InputSpec,
    generate_adversarial_inputs,
    generate_edge_inputs,
    generate_input_cases,
    generate_inputs,
    generate_representative_inputs,
)
from .localization import (
    DivergenceLocalizer,
    DivergenceLocation,
    LocalizationHook,
    first_divergent_path,
)
from .shrinking import InputShrinker, ShrinkPreconditionError, shrink_input

__all__ = [
    "BackendAdapter",
    "BackendError",
    "BackendSpec",
    "CallableAdapter",
    "CallableBackendAdapter",
    "ComparisonResult",
    "DivergenceLocation",
    "DivergenceLocalizer",
    "FunctionBackendAdapter",
    "GenericBackendAdapter",
    "InputCase",
    "InputSpec",
    "InputShrinker",
    "LocalizationHook",
    "ONNXAdapter",
    "ONNXRuntimeAdapter",
    "ONNXRuntimeBackendAdapter",
    "OnnxRuntimeBackendAdapter",
    "OptionalDependencyError",
    "OutputComparison",
    "ParityCaseResult",
    "ParityChecker",
    "ParityComparator",
    "ParityDivergence",
    "ParityReport",
    "ParityResult",
    "PyTorchAdapter",
    "PyTorchBackendAdapter",
    "RepresentativeInputGenerator",
    "ShrinkPreconditionError",
    "Tolerance",
    "TolerancePolicy",
    "Tolerances",
    "TorchAdapter",
    "TorchBackendAdapter",
    "as_adapter",
    "as_backend",
    "compare_batch",
    "compare_models",
    "compare_outputs",
    "first_divergent_path",
    "generate_adversarial_inputs",
    "generate_edge_inputs",
    "generate_input_cases",
    "generate_inputs",
    "generate_representative_inputs",
    "load_backend",
    "parity",
    "parse_backend_spec",
    "predict_batch",
    "shrink_input",
]
