"""Public core contracts and utilities."""

from .capsule import RunCapsule
from .capture import CaptureContext, CaptureHook
from .codecs import (
    CONTAINER_CODEC,
    BytesStateCodec,
    EncodedState,
    JsonStateCodec,
    NumpyStateCodec,
    StateCodec,
    StateCodecRegistry,
    TorchStateCodec,
    collect_artifact_digests,
    decode_state_tree,
    default_state_codecs,
    digest_state_tree,
    encode_state_tree,
)
from .contracts import (
    Budget,
    ExecutionResult,
    ExecutionSpec,
    PluginDescriptor,
    PredicateResult,
    RunGroup,
    ValidationCheck,
    ValidationPlan,
    WorkflowSession,
    evaluate_predicate,
    normalize_predicate_result,
)
from .errors import CheckpointUnavailable, IncompleteReplay, UnresolvedEvaluation, ValidationError
from .failure import exception_signature, normalize_exception_message, signature_from_record
from .index import index_path, load_index, record_run, resolve_run
from .models import (
    SCHEMA_VERSION,
    ArtifactRef,
    CheckpointRef,
    Comparison,
    Counterexample,
    DatasetRef,
    EvidenceState,
    EvidenceStatus,
    FailureSignature,
    Incident,
    LineageEdge,
    LineageNode,
    MetricSeries,
    ModelRef,
    Observation,
    ReplayPlan,
    ResourceSeries,
    RNGState,
    Run,
    StateSnapshot,
    TraceEvent,
    compatible_exception_types,
    utc_now,
)
from .serialization import dump_bytes, dumps, load, loads, validate
from .store import ArtifactStore, FsspecArtifactStore, LocalArtifactStore

__all__ = [
    "SCHEMA_VERSION",
    "ArtifactRef",
    "ArtifactStore",
    "BytesStateCodec",
    "CheckpointRef",
    "CheckpointUnavailable",
    "IncompleteReplay",
    "CaptureContext",
    "CaptureHook",
    "Comparison",
    "CONTAINER_CODEC",
    "Counterexample",
    "Budget",
    "ExecutionResult",
    "ExecutionSpec",
    "PluginDescriptor",
    "PredicateResult",
    "RunGroup",
    "UnresolvedEvaluation",
    "ValidationCheck",
    "ValidationPlan",
    "WorkflowSession",
    "collect_artifact_digests",
    "decode_state_tree",
    "digest_state_tree",
    "encode_state_tree",
    "evaluate_predicate",
    "normalize_predicate_result",
    "DatasetRef",
    "EncodedState",
    "EvidenceState",
    "EvidenceStatus",
    "FailureSignature",
    "FsspecArtifactStore",
    "Incident",
    "index_path",
    "JsonStateCodec",
    "LineageEdge",
    "LineageNode",
    "load_index",
    "LocalArtifactStore",
    "MetricSeries",
    "ModelRef",
    "NumpyStateCodec",
    "Observation",
    "RNGState",
    "ResourceSeries",
    "Run",
    "RunCapsule",
    "record_run",
    "ReplayPlan",
    "resolve_run",
    "StateCodec",
    "StateCodecRegistry",
    "StateSnapshot",
    "TraceEvent",
    "TorchStateCodec",
    "UnresolvedEvaluation",
    "ValidationError",
    "WorkflowSession",
    "dump_bytes",
    "dumps",
    "exception_signature",
    "load",
    "loads",
    "normalize_exception_message",
    "signature_from_record",
    "compatible_exception_types",
    "utc_now",
    "validate",
    "default_state_codecs",
]
